  
version: '3.7'

services:
   db:
     image: bahrsvenjasql
     restart: always
     ports:
        - "3306:3306"
     volumes:
        - type: volume
          source: dbdata
          target: /var/lib/mysql
     restart: always
     environment:
      DB_USER: svenjabahr
      DB_PASSWORD: passWord123
      DB_NAME: sd_lab3_sql
        
   wordpress:
     depends_on:
       - db
     image: bahrsvenjawp
     ports:
       - "80:80"
     volumes:
       - type: volume
         source: wpconfig
         target: /etc/wordpress/
       - type: volume
         source: wpuploads
         target: /var/www/html/wp-content/uploads/
     restart: always
     environment:
      DB_USER: svenjabahr
      DB_PASSWORD: passWord123
      DB_NAME: sd_lab3_wp
      DB_HOST: db:3306

volumes:
  dbdata:
  wpconfig:
  wpuploads: